### ISSUE TITLE
Integration with Microsoft Teams

### ISSUE THREAD

**Issue by iovcho** [pmansour/pimeet#16]
Hello. I reviewed the project but did not see integration with Microsoft Teams. The Minimeet extension is only for Google Meet. How can this be achieved with Microsoft Teams?
Thank you very much for your time.

**Comment by pmansour** [comment]
At the moment, only Google Meets is supported. This project mainly focuses on a browser-based video chatting, and Google Meets is a native browser-first experience. As such, all the Chrome Extension logic around authentication, finding and joining meetings is focused around Google authentication and Google Meet meetings.

It's theoretically possible to support Microsoft Teams meetings, but most likely that would have to be in the browser-version of Teams. I'm not sure how optimized Teams is for running in the browser (it may be too slow to run on a Raspberry Pi), or which features are available in the browser (e.g. finding and joining the next meeting). Either way, it would be a ton of work and require rewriting most of the minimeet extension and the other logic here.

So for now, you can just assume this is not supported. I also don't have any upcoming plans to add support for this myself. Your options are to either invest in a new project that supports Teams, or consider using Google Meets for your needs.
